# Generated by Django 4.1.3 on 2022-11-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stats",
            unique_together={("player", "game")},
        ),
    ]
